### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by liran-funaro** [cloudflare/stpyv8#63] opened 2022-12-22 10:07 UTC
I have a python program that repeatedly queries a JS object that returns a JSON object.
Then I transform the object into a Python `dict` as follows:
```python3
import json
json_js = ctx.eval("JSON")
my_obj_js = ctx.eval("new MyClass()")

def query():
    return json.loads(json_js.stringify(my_obj_js.query()))
```

This creates the following memory leak crash after multiple queries (~100K).
```
<--- Last few GCs --->

[1475783:0x55e049377380]   455427 ms: Scavenge (reduce) 1468.0 (1496.8) -> 1467.1 (1497.0) MB, 3.1 / 0.0 ms  (average mu = 0.132, current mu = 0.031) allocation failure; 
[1475783:0x55e049377380]   455473 ms: Scavenge (reduce) 1468.3 (1497.0) -> 1467.3 (1497.3) MB, 2.6 / 0.0 ms  (average mu = 0.132, current mu = 0.031) allocation failure; 


<--- JS stacktrace --->


#
# Fatal javascript OOM in Ineffective mark-compacts near heap limit
#
```

This happens even if I restart the js-context every few calls.

When I change my program to "stringify" the JSON object in the JS implementation of the class, then the memory leak is resolved.
```python3
def query():
    return json.loads(my_obj_js.jsonQuery())
```
where `my_obj_js.jsonQuery()` returns `JSON.stringify(this.query())`.

From the STPyV8 implementation, I see that when a string is returned, then it is copied into a Python string.
But when an object is returned, it is using a C++ shared pointer.
My guess is that Python does not decrease the pointer when the object is released.

### Runtime
```
$ python3 --version
Python 3.10.6
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
With `stpyv8-ubuntu-22.04-python-3.10.zip`.

**Comment by buffer** [comment] 2022-12-22 11:30
Thanks for reporting the issue. Can you please share a simplified example code that triggers this misbehaviour so that we can try reproducing it and hopefully fix? Thanks!

**Comment by liran-funaro** [comment] 2022-12-22 12:46
```python3
import json
import STPyV8

with STPyV8.JSContext() as ctxt:
    JSON = ctxt.eval("JSON")
    foo = ctxt.eval("""((i) => {
        return {
            'i': i,
            'a': Array(100_000).fill(i) 
        };
    })""")

    for i in range(int(1e9)):
        ret = json.loads(JSON.stringify(foo(i)))
        print(f"\rret: {ret['i']:,d}", end="")
```

Result:
```
ret: 1,920
<--- Last few GCs --->

[1542295:0x55f91c8487f0]    23407 ms: Scavenge (reduce) 1467.6 (1481.3) -> 1467.6 (1481.3) MB, 1.0 / 0.0 ms  (average mu = 0.095, current mu = 0.062) allocation failure; 
[1542295:0x55f91c8487f0]    23415 ms: Scavenge (reduce) 1468.1 (1481.8) -> 1467.1 (1481.3) MB, 0.7 / 0.0 ms  (average mu = 0.095, current mu = 0.062) allocation failure; 


<--- JS stacktrace --->


#
# Fatal javascript OOM in Ineffective mark-compacts near heap limit
#

'python3 memory_leak.py' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by liran-funaro** [comment] 2022-12-22 13:01
@buffer Interestingly, this does not happen when I avoid "stringify" the result.

```python3
import STPyV8

with STPyV8.JSContext() as ctxt:
    foo = ctxt.eval("""i => {
        return {
            'i': i,
            'a': Array(1<<20).fill(i) 
        };
    }""")

    for i in range(int(1e9)):
        ret = foo(i)
        print(f"\r#iter: {ret['i']:,d}", end="")
```

**Comment by liran-funaro** [comment] 2022-12-22 13:55
@buffer I created a new more succinct minimal example.
It seems that this issue occurs when I feed a `STPyV8.JSObject` back to a `JSFunction`.
```python3
import STPyV8

with STPyV8.JSContext() as ctxt:
    foo = ctxt.eval("""i => {
        return {
            'i': i,
            'a': Array(1<<20).fill(i) 
        };
    }""")
    bar = ctxt.eval("""o => o.i""")

    for i in range(int(1e9)):
        ret = bar(foo(i))
        print(f"\r#iter: {ret:,d}", end="")
```

Result:
```
#iter: 183
<--- Last few GCs --->

[1562232:0x5616daa6ec20]     2033 ms: Mark-Compact 1464.4 (1497.9) -> 1464.4 (1497.9) MB, 84.8 / 0.0 ms  (average mu = 0.052, current mu = 0.046) allocation failure; scavenge might not succeed
[1562232:0x5616daa6ec20]     2123 ms: Mark-Compact 1472.4 (1506.0) -> 1472.4 (1506.0) MB, 85.5 / 0.0 ms  (average mu = 0.048, current mu = 0.045) allocation failure; scavenge might not succeed


<--- JS stacktrace --->


#
# Fatal javascript OOM in Reached heap limit
#
```

**Comment by buffer** [comment] 2022-12-23 11:43
I think I spotted the reason behind this misbehaviour which seems related to the object lifecycle tracing. Can you confirm that commenting the line 

https://github.com/cloudflare/stpyv8/blob/master/src/Config.h#L7

and rebuilding is enough to avoid the crash for you too? In such case I will dive deep into the object lifecycle implementation to figure out what's wrong with it. Thanks!

**Comment by liran-funaro** [comment] 2022-12-23 14:13
@buffer Thanks. Commenting out this line solved the issue.

**Comment by buffer** [comment] 2022-12-23 14:14
Thanks for the feedback. I am already investigating the object lifecycle implementation. I will update the issue as soon as I figure out what is going on.

**Comment by buffer** [comment] 2022-12-28 10:53
While investigating the object lifecycle implementation I spotted some issues that are there since the beginning. FYI STPyV8 is a fork of the now unmaintained PyV8 and we made the assumption that such code just worked. I think we were wrong. Summarizing my findings here.

First of all, the PyV8 object lifecycle implementation makes the assumption that the GC is going to be invoked sooner or later and sets weak callbacks for the handles whose purpose should be to cleanup the living map. According to V8 documentation

_There is no guarantee as to when or even if the callback is invoked. The invocation is performed solely on a best effort basis. As always, GC-based finalization should not be relied upon for any critical form of resource management!_   

Moreover some methods in the current implementation use to return smart pointers' internal pointers after a release. Considering that weak callbacks are never invoked (at least it never happened in all the tests I performed) this way of managing the smart pointers is the perfect recipe for disaster as it can very easily lead to memory leak. Which is exactly what we observed.

I really suspect the code was broken even when it used to use _auto_ptr_ pointers instead of _unique_ptr_ pointers. For this reason I think I will disable the object lifecycle support until a not broken implementation will be available.

CC @philsyme

**Comment by liran-funaro** [comment] 2022-12-28 13:40
Thanks. I assume lifecycle tracing is only helpful for debugging. Can you confirm?

**Comment by buffer** [comment] 2022-12-28 13:50
Not really. It was introduced back in the PyV8 days in order to improve performances avoiding some already performed Python-JS object translations. You can see a simple example of how it is supposed to work at [1] 

[1] https://github.com/cloudflare/stpyv8/blob/master/src/Wrapper.cpp#L805

**Comment by buffer** [comment] 2023-01-12 11:07
@liran-funaro FYI I had to re-enable object lifecycle tracking before releasing v10.9.194.9 as I observed its lack broke some tests. BTW I think I could have spotted where the issue happens and I am already testing some alternative approaches to fix it. Hopefully a fix will be available before the next release.

**Comment by liran-funaro** [comment] 2023-01-15 11:15
Thanks for the update!

**Comment by buffer** [comment] 2023-01-25 09:23
@liran-funaro FYI I performed three commits in the branch _branch-11.0_ which should properly fix the issue. According to Chromium schedule, V8 branch 11.0 should be released as stable on February 7th so this gives me a few additional days to spot potential issues with the changes. Please feel free to test the new code and provide some feedback if you can. I am going to keep this issue open until STPyV8 version 11 release.

Detailing the changes here for tracking purposes

[1] improves _CIsolate::NearHeapLimitCallback_ invoking _AdjustAmountOfExternalAllocatedMemory_ if the heap size increase is lower than the maximum heap increase. This patch is not strictly required after the memory leak bug was actually fixed (see [2]) but it can help in other scenarios. According to V8 documentation 

_AdjustAmountOfExternalAllocatedMemory adjusts the amount of registered external memory. Used to give V8 an indication of the amount of externally allocated memory that is kept alive by JavaScript objects. V8 uses this to decide when to perform global garbage collections. Registering externally allocated memory will trigger global garbage collections more often than it would otherwise in an attempt to garbage collect the JavaScript objects that keep the externally allocated memory alive._

[2] actually fixes the bug. The patch both fixes the broken _ObjectTracer::WeakCallback_ and the way the object is tracked as performed by _CPythonObject::WrapInternal_

[3] introduces a new unittest check specifically designed to catch this misbehaviour. Note: running the test in its own isolate is just a way to avoid interactions with the default isolate. This is not usually required in the most common use cases 

[1] https://github.com/cloudflare/stpyv8/commit/a661c04906a696bceeeb7af7cdc49699dd22ba65
[2] https://github.com/cloudflare/stpyv8/commit/17ddccb4cd59f0edeeb14a6635aefab8e46943ec
[3] https://github.com/cloudflare/stpyv8/commit/98e7ad768d0ba517020125e314bb4258e91a68b2

CC @philsyme

**Comment by liran-funaro** [comment] 2023-01-29 10:08
Thanks for the update.
I've compiled the branch and tested it on my workload.
It seems to perform well and with no memory leaks.

**Closed** 2023-02-22 13:55 UTC
Labels: bug
